version: '3'
services:
  app:
    build:
      context: ./
    depends_on:
      - database
    image: n-app
    #volumes設定
    volumes:
     - "./app:/src"
    # コンテナ名
    container_name: n-app
    # ポート接続
    ports:                          
      - 8000:8000
    environment:
      SECRET_KEY: secret
      PORT: 8000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mydatabase
    tty: true

  database:
    image: postgres:12.3
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: mydatabase
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust